# coding: utf-8

"""
    Deep Image

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deep_image_ai_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_rest_api_process_post(self) -> None:
        """Test case for rest_api_process_post

        Schedules a job to perform selected enhancement options.
        """
        pass

    def test_rest_api_process_result_post(self) -> None:
        """Test case for rest_api_process_result_post

        Schedules a job to perform selected enhancement options and waits for the result.
        """
        pass

    def test_rest_api_result_hash_get(self) -> None:
        """Test case for rest_api_result_hash_get

        Returns processing job result.
        """
        pass


if __name__ == '__main__':
    unittest.main()
