# coding: utf-8

"""
    Deep Image

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deep_image_ai_client.models.crop_types import CropTypes

class TestCropTypes(unittest.TestCase):
    """CropTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCropTypes(self):
        """Test CropTypes"""
        # inst = CropTypes()

if __name__ == '__main__':
    unittest.main()
