# coding: utf-8

"""
    Deep Image

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deep_image_ai_client.models.background_remove_types import BackgroundRemoveTypes

class TestBackgroundRemoveTypes(unittest.TestCase):
    """BackgroundRemoveTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBackgroundRemoveTypes(self):
        """Test BackgroundRemoveTypes"""
        # inst = BackgroundRemoveTypes()

if __name__ == '__main__':
    unittest.main()
