# coding: utf-8

"""
    Deep Image

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deep_image_ai_client.models.background_parameters import BackgroundParameters

class TestBackgroundParameters(unittest.TestCase):
    """BackgroundParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BackgroundParameters:
        """Test BackgroundParameters
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BackgroundParameters`
        """
        model = BackgroundParameters()
        if include_optional:
            return BackgroundParameters(
                remove = 'auto',
                color = 'white',
                replace = 'https://deep-image.ai/api-example2.jpg',
                generate = deep_image_ai_client.models.generate_parameters.GenerateParameters(
                    description = '', 
                    item_area_percentage = 0.5, 
                    sample_num = 56, 
                    color = 'white', 
                    additional_prompt = '', 
                    negative_prompt = '', 
                    adapter_type = 'generate_background', )
            )
        else:
            return BackgroundParameters(
        )
        """

    def testBackgroundParameters(self):
        """Test BackgroundParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
