# coding: utf-8

"""
    Deep Image

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deep_image_ai_client.models.preset_types import PresetTypes

class TestPresetTypes(unittest.TestCase):
    """PresetTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPresetTypes(self):
        """Test PresetTypes"""
        # inst = PresetTypes()

if __name__ == '__main__':
    unittest.main()
